In [ ]:
"""
Problem 1
Matrix product is calculated manually
"""

<div style="text-align: right">

$ A = \begin{bmatrix} -1 & 2 & 3 \\ 4 & -5 & 6 \\ 7 & 8 & -9 \end{bmatrix} $ <br>
$ B = \begin{bmatrix} 0 & 2 & 1 \\ 0 & 2 & -8 \\ 2 & 9 & -1 \end{bmatrix} $
<br>
$ C = \begin{bmatrix} c_{11} & c_{12} & c_{13} \\ c_{21} & c_{22} & c_{23} \\ c_{31} & c_{32} & c_{33} \end{bmatrix} $

<br>
$ c_{11} = (-1) \times 0 + 2 \times 0 + 3 \times 2 = 6 $ <br>
$ c_{21} = 4 \times 0 + (-5) \times 0 + 6 \times 2 = 12 $ <br>
$ c_{31} = 7 \times 0 + 8 \times 0 + (-9) \times 2 = -18 $ <br>

$ c_{12} = (-1) \times 2 + 2 \times 2 + 3 \times 9 = 29 $ <br>
$ c_{22} = 4 \times 2 + (-5) \times 2 + 6 \times 9 = 52 $ <br>
$ c_{32} = 7 \times 2 + 8 \times 2 + (-9) \times 9 = -51 $ <br>

$ c_{13} = (-1) \times 1 + 2 \times (-8) + 3 \times (-1) = -20 $ <br>
$ c_{23} = 4 \times 1 + (-5) \times (-8) + 6 \times (-1) = 38 $ <br>
$ c_{33} = 7 \times 1 + 8 \times (-8) + -9 \times (-1) = -48 $ <br>
<br><br>

$ C = \begin{bmatrix} 6 & 29 & -20 \\ 12 & 52 & 38 \\ -18 &-51 & -48 \end{bmatrix} $

</div>

In [22]:
"""
Problem 2
Calculation by NumPy function
"""

import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

c_ndarray = a_ndarray @ b_ndarray

print('Dot product of A and B:')
print(c_ndarray)

Dot product of A and B:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [23]:
"""
Problem 3
Implementation of calculation of a certain element
"""

c_00 = 0.0

for i in range(3):
  c_00 = a_ndarray[0][i] * b_ndarray[i][0]

print(f"Value of C[0][0]: {c_00}") 

Value of C[0][0]: 6


In [24]:
"""
Problem 4
Creating a function that performs matrix multiplication
"""

def matrix_multiplication(a, b):
  c = np.zeros((a.shape[0], b.shape[1]))

  for i in range(a.shape[0]):
    for j in range(b.shape[1]):
      for k in range(b.shape[1]):
        c[i][j] += a[i][k] * b[k][j]

  return c

c = matrix_multiplication(a_ndarray, b_ndarray)
print('Matrix multiplication of A and B \nC:')
print(c)

Matrix multiplication of A and B 
C:
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [38]:
"""
Problem 5
Judge the input whose calculation is not defined
"""

def matrix_multiplication(a, b):
  if a.shape[1] != b.shape[0]:
    print("Incorrect input dimension")
    return None

  c = np.zeros((a.shape[0], b.shape[1]))

  for i in range(a.shape[0]):
    for j in range(b.shape[1]):
      for k in range(b.shape[1]):
        c[i][j] += a[i][k] * b[k][j]

  return c

a_test = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_test = np.array([[0, 2], [0, 2]])

print('Valid multiplication \nC:')
c = matrix_multiplication(a_ndarray, b_ndarray)
print(c)

print('\nInvalid multiplication \nC:')
c_test = matrix_multiplication(a_test, b_test)
print(c_test)

Valid multiplication 
C:
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]

Invalid multiplication 
C:
Incorrect input dimension
None


In [39]:
"""
Problem 6
Transposition
"""

a = np.array([[1, 2, 3], [4, 5, 6]]) # 2 x 3
b = np.array([[1, 2, 3], [5, 6, 7], [9, 10, 11], [13, 14, 15]]) # 4 x 3

c = np.dot(a, b_transpose) # 2 x 4
print(c)

[[ 14  38  62  86]
 [ 32  92 152 212]]
